### ISSUE TITLE
Fatal error when the connection is force closed in Rabbit MQ admin panel

### ISSUE THREAD

**Issue by andyto** [NumminorihSF/bramqp-wrapper#1]
In the RabbitMq admin panel, when the Amqp connection is force closed, it will encounter the following error. The socket error doesn't seems to be handled in this case.

```
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:268:12)
    at ConnectionHandle.heartbeat (/Users/user/Desktop/Projects/test-core/node_modules/bramqp/lib/connectionHandle.js:371:14)
    at null._repeat (/Users/user/Desktop/Projects/test-core/node_modules/bramqp-wrapper/lib/client.js:121:51)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.j
```

**Comment by NumminorihSF** [comment]
It looks, like a bug with bramqp,  but I will test it tomorow. Thanks

**Comment by NumminorihSF** [comment]
Yes. There is a bug with bramqp. It does nothing on socket closing. Also, there was a bug with close connection from application (node), Interval with heartbeat was not clearing.
I created one PR with Interval and now I am creating another one with connection state watching, to not throwing errors on closed connection, but returning them to callbacks.

**Comment by andyto** [comment]
Great! I was working my way through a "reconnect-able" RabbitMq connection, but it seem that the Node.js library don't handle most of the case.

I have tested a few situations:
1. Killing the Amqp connections from RabbitMq admin panel as above
2. Do a "Kill" command to RabbitMq damon

In both case, Bramqp will just throw exceptions. Also, reconnection to Bramqp is a bit of a hack due to it's listener for socket open in https://github.com/bakkerthehacker/bramqp/blob/master/lib/connectionHandle.js

Anyway, great job. I really love your wrapper, it makes it much easier to use!

**Comment by NumminorihSF** [comment]
Bramqp was updated, to fix bugs. I update dependency and fix some my code. Now it works fine. Update to version 0.11.1
